// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAspN_0mRe-jCxkkcwqL0MVwGN_lF_qqIc',
    appId: '1:794176014644:web:d7699e063d9d55de37fd61',
    messagingSenderId: '794176014644',
    projectId: 'todo-e4a1e',
    authDomain: 'todo-e4a1e.firebaseapp.com',
    databaseURL: 'https://todo-e4a1e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-e4a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0uYVCWH12aYnOGYMokQ2C-c7wZB_u1Cw',
    appId: '1:794176014644:ios:9262160b65ae63b137fd61',
    messagingSenderId: '794176014644',
    projectId: 'todo-e4a1e',
    databaseURL: 'https://todo-e4a1e-default-rtdb.firebaseio.com',
    storageBucket: 'todo-e4a1e.appspot.com',
    iosClientId: '794176014644-epqp19nvhaghg44cgrmonek308hgfiiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
